# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Lin\Desktop\ProjectFisher\path\planning.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(803, 601)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mapbox = QtWidgets.QGroupBox(self.centralwidget)
        self.mapbox.setGeometry(QtCore.QRect(9, 9, 500, 500))
        self.mapbox.setObjectName("mapbox")
        self.planbutton = QtWidgets.QPushButton(self.centralwidget)
        self.planbutton.setGeometry(QtCore.QRect(570, 10, 171, 51))
        self.planbutton.setObjectName("planbutton")
        self.showbutton = QtWidgets.QPushButton(self.centralwidget)
        self.showbutton.setGeometry(QtCore.QRect(570, 80, 171, 51))
        self.showbutton.setObjectName("showbutton")
        self.remapbutton = QtWidgets.QPushButton(self.centralwidget)
        self.remapbutton.setGeometry(QtCore.QRect(570, 150, 171, 51))
        self.remapbutton.setObjectName("remapbutton")
        self.upbutton = QtWidgets.QPushButton(self.centralwidget)
        self.upbutton.setGeometry(QtCore.QRect(570, 220, 171, 51))
        self.upbutton.setObjectName("upbutton")
        self.downbutton = QtWidgets.QPushButton(self.centralwidget)
        self.downbutton.setGeometry(QtCore.QRect(570, 290, 171, 51))
        self.downbutton.setObjectName("downbutton")
        self.leftbutton = QtWidgets.QPushButton(self.centralwidget)
        self.leftbutton.setGeometry(QtCore.QRect(570, 360, 171, 51))
        self.leftbutton.setObjectName("leftbutton")
        self.rightbutton = QtWidgets.QPushButton(self.centralwidget)
        self.rightbutton.setGeometry(QtCore.QRect(570, 430, 171, 51))
        self.rightbutton.setObjectName("rightbutton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 803, 23))
        self.menubar.setObjectName("menubar")
        self.menustart = QtWidgets.QMenu(self.menubar)
        self.menustart.setObjectName("menustart")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menustart.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.mapbox.setTitle(_translate("MainWindow", "map"))
        self.planbutton.setText(_translate("MainWindow", "A* algorithm"))
        self.showbutton.setText(_translate("MainWindow", "Show path planning"))
        self.remapbutton.setText(_translate("MainWindow", "Remapping"))
        self.upbutton.setToolTip(_translate("MainWindow", "hold w"))
        self.upbutton.setText(_translate("MainWindow", "Up(W)"))
        self.upbutton.setShortcut(_translate("MainWindow", "W"))
        self.downbutton.setToolTip(_translate("MainWindow", "hold s down"))
        self.downbutton.setText(_translate("MainWindow", "Down(S)"))
        self.downbutton.setShortcut(_translate("MainWindow", "S"))
        self.leftbutton.setToolTip(_translate("MainWindow", "hold a to move left"))
        self.leftbutton.setText(_translate("MainWindow", "Left(A)"))
        self.leftbutton.setShortcut(_translate("MainWindow", "A"))
        self.rightbutton.setToolTip(_translate("MainWindow", "hold d to move right"))
        self.rightbutton.setText(_translate("MainWindow", "Right(D)"))
        self.rightbutton.setShortcut(_translate("MainWindow", "D"))
        self.menustart.setTitle(_translate("MainWindow", "start"))
